using System.Collections.Generic;

public class XPTable
{
	public static Dictionary<string, int> XPEarned;

	public static Dictionary<string, string> XPDetail;

	public static void InitXpValues()
	{
		XPEarned = new Dictionary<string, int>();
		XPDetail = new Dictionary<string, string>();
		XPEarned.Add("FoursHiteasy", 40);
		XPDetail.Add("FoursHiteasy", "Four Scored");
		XPEarned.Add("FoursHitmedium", 48);
		XPDetail.Add("FoursHitmedium", "Four Scored");
		XPEarned.Add("FoursHithard", 64);
		XPDetail.Add("FoursHithard", "Four Scored");
		XPEarned.Add("MaidenOvereasy", 120);
		XPDetail.Add("MaidenOvereasy", "Maiden Over Bowled");
		XPEarned.Add("MaidenOvermedium", 144);
		XPDetail.Add("MaidenOvermedium", "Maiden Over Bowled");
		XPEarned.Add("MaidenOverhard", 192);
		XPDetail.Add("MaidenOverhard", "Maiden Over Bowled");
		XPEarned.Add("DotBalleasy", 20);
		XPDetail.Add("DotBalleasy", "Dot Ball Bowled");
		XPEarned.Add("DotBallmedium", 20);
		XPDetail.Add("DotBallmedium", "Dot Ball Bowled");
		XPEarned.Add("DotBallhard", 20);
		XPDetail.Add("DotBallhard", "Dot Ball Bowled");
		XPEarned.Add("SixHiteasy", 60);
		XPDetail.Add("SixHiteasy", "Six Scored");
		XPEarned.Add("SixHitmedium", 72);
		XPDetail.Add("SixHitmedium", "Six Scored");
		XPEarned.Add("SixHithard", 96);
		XPDetail.Add("SixHithard", "Six Scored");
		XPEarned.Add("Bowledeasy", 60);
		XPDetail.Add("Bowledeasy", "Bowled");
		XPEarned.Add("Bowledmedium", 72);
		XPDetail.Add("Bowledmedium", "Bowled");
		XPEarned.Add("Bowledhard", 96);
		XPDetail.Add("Bowledhard", "Bowled");
		XPEarned.Add("Caughteasy", 40);
		XPDetail.Add("Caughteasy", "Caught");
		XPEarned.Add("Caughtmedium", 48);
		XPDetail.Add("Caughtmedium", "Caught");
		XPEarned.Add("Caughthard", 64);
		XPDetail.Add("Caughthard", "Caught");
		XPEarned.Add("WicketOtherseasy", 30);
		XPDetail.Add("WicketOtherseasy", "RunOut");
		XPEarned.Add("WicketOthersmedium", 36);
		XPDetail.Add("WicketOthersmedium", "RunOut");
		XPEarned.Add("WicketOthershard", 48);
		XPDetail.Add("WicketOthershard", "RunOut");
		XPEarned.Add("Fiftyeasy", 100);
		XPDetail.Add("Fiftyeasy", "Fifty");
		XPEarned.Add("Fiftymedium", 120);
		XPDetail.Add("Fiftymedium", "Fifty");
		XPEarned.Add("Fiftyhard", 160);
		XPDetail.Add("Fiftyhard", "Fifty");
		XPEarned.Add("Centuryeasy", 200);
		XPDetail.Add("Centuryeasy", "Century");
		XPEarned.Add("Centurymedium", 240);
		XPDetail.Add("Centurymedium", "Century");
		XPEarned.Add("Centuryhard", 320);
		XPDetail.Add("Centuryhard", "Century");
		XPEarned.Add("PerOverPlayedeasy", 10);
		XPDetail.Add("PerOverPlayedeasy", "PerOverPlayed");
		XPEarned.Add("PerOverPlayedmedium", 12);
		XPDetail.Add("PerOverPlayedmedium", "PerOverPlayed");
		XPEarned.Add("PerOverPlayedhard", 16);
		XPDetail.Add("PerOverPlayedhard", "PerOverPlayed");
		XPEarned.Add("2OverMatchWonEasy", 200);
		XPEarned.Add("2OverMatchWonMedium", 240);
		XPEarned.Add("2OverMatchWonHard", 320);
		XPEarned.Add("5OverMatchWonEasy", 500);
		XPEarned.Add("5OverMatchWonMedium", 600);
		XPEarned.Add("5OverMatchWonHard", 800);
		XPEarned.Add("10OverMatchWonEasy", 1000);
		XPEarned.Add("10OverMatchWonMedium", 1200);
		XPEarned.Add("10OverMatchWonHard", 1600);
		XPEarned.Add("20OverMatchWonEasy", 2000);
		XPEarned.Add("20OverMatchWonMedium", 2400);
		XPEarned.Add("20OverMatchWonHard", 3200);
		XPEarned.Add("30OverMatchWonEasy", 3000);
		XPEarned.Add("30OverMatchWonMedium", 3600);
		XPEarned.Add("30OverMatchWonHard", 4800);
		XPEarned.Add("50OverMatchWonEasy", 5000);
		XPEarned.Add("50OverMatchWonMedium", 6000);
		XPEarned.Add("50OverMatchWonHard", 8000);
		XPEarned.Add("KnockoutGroupQualifierWon", 2);
		XPDetail.Add("KnockoutGroupQualifierWon", "Win knockout stage 1");
		XPEarned.Add("KnockoutWinQuarterFinal", 6);
		XPDetail.Add("KnockoutWinQuarterFinal", "Win Quarter Finals");
		XPEarned.Add("KnockoutReachSemifinal", 8);
		XPDetail.Add("KnockoutReachSemifinal", "Reach Semi Finals");
		XPEarned.Add("KnockoutWinSemifinal", 10);
		XPDetail.Add("KnockoutWinSemifinal", "Win Semi Finals");
		XPEarned.Add("KnockoutReachFinal", 12);
		XPDetail.Add("KnockoutReachFinal", "Runner Up");
		XPEarned.Add("KnockoutWinFinal", 15);
		XPDetail.Add("KnockoutWinFinal", "Knockout Champion!");
		XPEarned.Add("NPLQualifier1Won", 8);
		XPDetail.Add("NPLQualifier1Won", "Reach finals");
		XPEarned.Add("NPLQualifier2Won", 6);
		XPDetail.Add("NPLQualifier2Won", "Reach finals");
		XPEarned.Add("NPLQualifier2Lost", 5);
		XPDetail.Add("NPLQualifier2Lost", "Finish third");
		XPEarned.Add("NPLEliminatorWon", 4);
		XPDetail.Add("NPLEliminatorWon", "Win eliminator round");
		XPEarned.Add("NPLEliminatorLost", 3);
		XPDetail.Add("NPLEliminatorLost", "Finish in top 4");
		XPEarned.Add("NPLLoseFinal", 10);
		XPDetail.Add("NPLLoseFinal", "NPL Runner Up");
		XPEarned.Add("NPLWinFinal", 12);
		XPDetail.Add("NPLWinFinal", "NPL INDIA Champion!");
		XPEarned.Add("WCQuarterFinalLost", 4);
		XPDetail.Add("WCQuarterFinalLost", "Reach World Cup Quarter Finals");
		XPEarned.Add("WCWinQuarterFinal", 6);
		XPDetail.Add("WCWinQuarterFinal", "Win World Cup Quarter Finals");
		XPEarned.Add("WCReachSemifinal", 8);
		XPDetail.Add("WCReachSemifinal", "Reach World Cup Semi Finals");
		XPEarned.Add("WCWinSemifinal", 10);
		XPDetail.Add("WCWinSemifinal", "Win World Cup Semi Finals");
		XPEarned.Add("WCReachFinalEasy", 500);
		XPDetail.Add("WCReachFinalEasy", "World Cup Runner Up");
		XPEarned.Add("WCReachFinalMedium", 600);
		XPDetail.Add("WCReachFinalMedium", "World Cup Runner Up");
		XPEarned.Add("WCReachFinalHard", 800);
		XPDetail.Add("WCReachFinalHard", "World Cup Runner Up");
		XPEarned.Add("WCWinFinalEasy", 1500);
		XPDetail.Add("WCWinFinalEasy", "World Cricket Champion!");
		XPEarned.Add("WCWinFinalMedium", 1800);
		XPDetail.Add("WCWinFinalMedium", "World Cricket Champion!");
		XPEarned.Add("WCWinFinalHard", 2400);
		XPDetail.Add("WCWinFinalHard", "World Cricket Champion!");
	}
}
